name: clearfilters-17

services:
  db17:
    image: postgres:15
    container_name: clearfilters-pg-17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "7417:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped

  odoo17:
    build: .
    container_name: clearfilters-odoo-17
    depends_on:
      - db17
    ports:
      - "10417:8069"
    environment:
      HOST: db17
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons/no_clear_all_filters:/mnt/extra-addons/no_clear_all_filters
    restart: unless-stopped

volumes:
  postgres_data:
  odoo_data:
