name: clearfilters-18

services:
  db18:
    image: postgres:16
    container_name: clearfilters-pg-18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "7418:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped

  odoo18:
    build: .
    container_name: clearfilters-odoo-18
    depends_on:
      - db18
    ports:
      - "10418:8069"
    environment:
      HOST: db18
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons/no_clear_all_filters:/mnt/extra-addons/no_clear_all_filters
    restart: unless-stopped

volumes:
  postgres_data:
  odoo_data:
