[options]
addons_path = /mnt/extra-addons
db_host = db17
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$N0ZIqRVibA0BoJQyhjCGMA$5OLw.O/3nzveaBGByGdW3KoJ3J6GtbaLqXq8P.CZqYZfGMV.3aDLfHp2wtYTk7b39S/ZsRESCd6XIYFXwD2PDQ

